const state={questions:[],currentIndex:0,answers:{},result:null};
const els={candidateName:document.getElementById("candidateName"),candidateEmail:document.getElementById("candidateEmail"),progressText:document.getElementById("progressText"),answeredText:document.getElementById("answeredText"),progressFill:document.getElementById("progressFill"),startBtn:document.getElementById("startBtn"),prevBtn:document.getElementById("prevBtn"),nextBtn:document.getElementById("nextBtn"),submitBtn:document.getElementById("submitBtn"),resetBtn:document.getElementById("resetBtn"),welcomeCard:document.getElementById("welcomeCard"),quizCard:document.getElementById("quizCard"),resultsCard:document.getElementById("resultsCard"),domainPill:document.getElementById("domainPill"),subcategoryPill:document.getElementById("subcategoryPill"),difficultyPill:document.getElementById("difficultyPill"),weightPill:document.getElementById("weightPill"),questionText:document.getElementById("questionText"),choicesWrap:document.getElementById("choicesWrap"),readinessBand:document.getElementById("readinessBand"),resultSummary:document.getElementById("resultSummary"),overallWeighted:document.getElementById("overallWeighted"),overallRaw:document.getElementById("overallRaw"),overallAnswered:document.getElementById("overallAnswered"),completedDate:document.getElementById("completedDate"),domainScores:document.getElementById("domainScores"),growthAreas:document.getElementById("growthAreas")};
async function init(){const res=await fetch("./questions.json");state.questions=await res.json();updateProgress()}
function startAssessment(){els.welcomeCard.classList.add("hidden");els.resultsCard.classList.add("hidden");els.quizCard.classList.remove("hidden");renderQuestion()}
function renderQuestion(){const q=state.questions[state.currentIndex];els.domainPill.textContent=prettyDomain(q.domain);els.subcategoryPill.textContent=q.subcategory.replaceAll("_"," ");els.difficultyPill.textContent=q.difficulty;els.weightPill.textContent=`Weight ${q.weight}`;els.questionText.textContent=q.question;els.choicesWrap.innerHTML="";["A","B","C","D"].forEach(letter=>{const choice=document.createElement("button");choice.className=`choice ${state.answers[q.question_id]===letter?"selected":""}`;choice.innerHTML=`<div class="choice-letter">${letter}</div><div class="choice-copy">${escapeHtml(q[`option_${letter.toLowerCase()}`])}</div>`;choice.addEventListener("click",()=>{state.answers[q.question_id]=letter;renderQuestion();updateProgress()});els.choicesWrap.appendChild(choice)});els.prevBtn.disabled=state.currentIndex===0;els.nextBtn.disabled=state.currentIndex>=state.questions.length-1;updateProgress()}
function nextQuestion(){state.currentIndex=Math.min(state.currentIndex+1,state.questions.length-1);renderQuestion()}
function prevQuestion(){state.currentIndex=Math.max(state.currentIndex-1,0);renderQuestion()}
function resetAssessment(){state.currentIndex=0;state.answers={};state.result=null;els.quizCard.classList.add("hidden");els.resultsCard.classList.add("hidden");els.welcomeCard.classList.remove("hidden");updateProgress()}
function computeResult(){let rawCorrect=0,weightedEarned=0,weightedPossible=0;const domainStats={},subStats={};state.questions.forEach(q=>{const answer=state.answers[q.question_id];const correct=answer===q.correct_answer;const weight=Number(q.weight);weightedPossible+=weight;if(correct){rawCorrect+=1;weightedEarned+=weight}domainStats[q.domain]??={domain:q.domain,correct:0,total:0,earned:0,possible:0};domainStats[q.domain].total+=1;domainStats[q.domain].possible+=weight;if(correct){domainStats[q.domain].correct+=1;domainStats[q.domain].earned+=weight}const subKey=`${q.domain}::${q.subcategory}`;subStats[subKey]??={domain:q.domain,subcategory:q.subcategory,misses:0,total:0};subStats[subKey].total+=1;if(!correct)subStats[subKey].misses+=1});const domainScores=Object.values(domainStats).map(d=>({domain:d.domain,correct:d.correct,total:d.total,weightedPercent:round2(d.earned/d.possible*100),status:statusForPercent(d.earned/d.possible*100)})).sort((a,b)=>a.weightedPercent-b.weightedPercent);const weakAreas=Object.values(subStats).filter(x=>x.misses>0).sort((a,b)=>(b.misses/b.total)-(a.misses/a.total)).slice(0,8).map(x=>({domain:x.domain,subcategory:x.subcategory,misses:x.misses,total:x.total,missRate:round2(x.misses/x.total*100)}));const overallPercent=round2(weightedEarned/weightedPossible*100);state.result={candidateName:els.candidateName.value.trim()||"Unnamed candidate",candidateEmail:els.candidateEmail.value.trim(),rawCorrect,total:state.questions.length,answered:Object.keys(state.answers).length,overallPercent,readinessBand:readinessBand(overallPercent,domainScores),domainScores,weakAreas,completedAt:new Date().toLocaleString()};renderResults()}
function renderResults(){const r=state.result;els.quizCard.classList.add("hidden");els.welcomeCard.classList.add("hidden");els.resultsCard.classList.remove("hidden");els.readinessBand.textContent=r.readinessBand;els.resultSummary.textContent=`${r.candidateName} completed the assessment${r.candidateEmail?` (${r.candidateEmail})`:""}.`;els.overallWeighted.textContent=`${r.overallPercent}%`;els.overallRaw.textContent=`${r.rawCorrect}/${r.total}`;els.overallAnswered.textContent=`${r.answered}`;els.completedDate.textContent=r.completedAt;els.domainScores.innerHTML="";r.domainScores.forEach(d=>{const row=document.createElement("div");row.className="bar-row";row.innerHTML=`<div class="bar-head"><span>${prettyDomain(d.domain)}</span><span>${d.weightedPercent}% (${d.correct}/${d.total})</span></div><div class="bar-track"><div class="bar-fill" style="width:${d.weightedPercent}%"></div></div>`;els.domainScores.appendChild(row)});els.growthAreas.innerHTML=r.weakAreas.length?`<ul>${r.weakAreas.map(x=>`<li><strong>${prettyDomain(x.domain)}</strong> — ${x.subcategory.replaceAll("_"," ")}: missed ${x.misses}/${x.total} (${x.missRate}%)</li>`).join("")}</ul>`:"<p>No major gaps detected.</p>"}
function updateProgress(){const total=state.questions.length||100;const answered=Object.keys(state.answers).length;const qNum=state.questions.length?Math.min(state.currentIndex+1,state.questions.length):0;els.progressText.textContent=state.questions.length?`Question ${qNum} of ${total}`:"Loading questions";els.answeredText.textContent=`${answered} / ${total}`;els.progressFill.style.width=`${answered/total*100}%`}
function prettyDomain(domain){const map={linux:"Linux",windows:"Windows",networking:"Networking",identity_pki:"Identity / PKI",splunk_data_ingest:"Splunk Data Ingest",splunk_search_architecture:"Splunk Search Architecture",splunk_auth_security:"Splunk Auth / Security",splunk_clustering_scaling:"Splunk Clustering / Scaling",splunk_operations_troubleshooting:"Splunk Ops / Troubleshooting",splunk_design_judgment:"Splunk Design Judgment"};return map[domain]||domain.replaceAll("_"," ")}
function statusForPercent(score){if(score>=90)return"Strong";if(score>=80)return"Ready";if(score>=70)return"Developing";return"Needs work"}
function readinessBand(score,domainScores){const lowSplunk=domainScores.filter(d=>d.domain.startsWith("splunk_")&&d.weightedPercent<65).length;if(score<70||lowSplunk>2)return"Not Ready";if(score<80)return"Developing";if(score<90)return"Near Ready";return"Ready"}
function round2(n){return Math.round((n+Number.EPSILON)*100)/100}
function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
els.startBtn.addEventListener("click",startAssessment);els.prevBtn.addEventListener("click",prevQuestion);els.nextBtn.addEventListener("click",nextQuestion);els.submitBtn.addEventListener("click",computeResult);els.resetBtn.addEventListener("click",resetAssessment);init();